### PR TITLE
copy and input color

### LINKED ISSUE #16: check if the input color is valid
Change the color only if it is valid otherwise leave the field unchanged.

### PR DESCRIPTION
**Pull request by g7i**
[Feature]
- Check if the input color is valid or not close: #16 

[Bugfixes]
- Included changes from #11 
- Fixed event handler for input color field

### CODE REVIEW

**Comment by g7i** [comment]
@Nitesh-thapliyal @abhigoyani

**Comment by g7i** [comment]
Plz visit [here](https://g7i.github.io/BG-Color-Switch/) to see the preview of this PR.

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
✅✅

**Review by kevalvavaliya — APPROVED** [review]

**Review by harikanani — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
@all-contributors please add @g7i  for code

**Pull request merged**
