### PR TITLE
Favicon generated

### PR DESCRIPTION
**Pull request by shruti73**
I have generated a favicon.

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
can you add a link to favicon as right now you have added the location of the image of your local system

**Comment by shruti73** [comment]
I have uploaded image in image folder

**Comment by adityamangal1** [comment]
I think there is something wrong. We can't see your commit you need to manually upload the image in that path. Join our discord server if you have more queries here - https://discord.com/invite/yWA37Sd7Cj

**Comment by shruti73** [comment]
How can i do that?
Can you help me out?

**Pull request closed without merging**
