### PR TITLE
New BG Color Switch!

### PR DESCRIPTION
**Pull request by Piyush-Chandel7**

### CODE REVIEW

**Comment by Nitesh-thapliyal** [comment]
> _No description provided._

can you provide a description of what exactly changes you have made and can you provide the screenshot of the changes made, it will be helpful😊

**Comment by Piyush-Chandel7** [comment]
Sure!
1. created a new button!
2. added ripple animation to the button!
3. created external JS file instead of inline JS!

here's the final result screenshot!
Capture

**Review by abhigoyani — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
Badhai ho 🎉

**Comment by adityamangal1** [comment]
@all-contributors please add @Piyush-Codes7  for code contribution

**Pull request merged**
